//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThaiWood.ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TestString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThaiWood.ViewRes.TestString", typeof(TestString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring Me Back Home!!!.
        /// </summary>
        public static string Error_BringBack {
            get {
                return ResourceManager.GetString("Error_BringBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uh... So it looks like you break something. The page you are looking for has up and vanished..
        /// </summary>
        public static string Error_Description {
            get {
                return ResourceManager.GetString("Error_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We Couldn’t Find This Page.
        /// </summary>
        public static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TanNhatTrung.
        /// </summary>
        public static string Name_Company {
            get {
                return ResourceManager.GetString("Name_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string String_AboutUs {
            get {
                return ResourceManager.GetString("String_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31 Ong Nuoc Tho D1800 mm street, Tan Hoa, Dong Hoa ward, Di An town, Binh Duong.
        /// </summary>
        public static string String_Address {
            get {
                return ResourceManager.GetString("String_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string String_AddToCart {
            get {
                return ResourceManager.GetString("String_AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to compare.
        /// </summary>
        public static string String_AddToCompare {
            get {
                return ResourceManager.GetString("String_AddToCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to wishlist.
        /// </summary>
        public static string String_AddToWishList {
            get {
                return ResourceManager.GetString("String_AddToWishList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string String_Brand {
            get {
                return ResourceManager.GetString("String_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string String_Category {
            get {
                return ResourceManager.GetString("String_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Founded in 2012, Tan Nhat Trung Co. Ltd. Specialise in wood products and forestry plantation management. The company main target is to supply hardwood timber, veeners, MDF, HDF and wood pellets. We try to aim to the non-waste production from manufacturing to recycling by-products. 
        ///Tan NhatTrung group has established itself with a firm commitment to bring not only high quality products but also ensure and protect environmental conditions. Our goal is to continue to pursuit of new materials, clever designs  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string String_CompanyInfo {
            get {
                return ResourceManager.GetString("String_CompanyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Info.
        /// </summary>
        public static string String_ContactInfo {
            get {
                return ResourceManager.GetString("String_ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string String_ContactUs {
            get {
                return ResourceManager.GetString("String_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2016 TanNhatTrung Co. Ltd. All rights reserved..
        /// </summary>
        public static string String_CopyRight {
            get {
                return ResourceManager.GetString("String_CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood Product Dealer.
        /// </summary>
        public static string String_Description {
            get {
                return ResourceManager.GetString("String_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed by.
        /// </summary>
        public static string String_DesignBy {
            get {
                return ResourceManager.GetString("String_DesignBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string String_Detail {
            get {
                return ResourceManager.GetString("String_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string String_Email {
            get {
                return ResourceManager.GetString("String_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@tannhattrung.com.
        /// </summary>
        public static string String_EmailSupport {
            get {
                return ResourceManager.GetString("String_EmailSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string String_Fax {
            get {
                return ResourceManager.GetString("String_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Items.
        /// </summary>
        public static string String_FeatureItem {
            get {
                return ResourceManager.GetString("String_FeatureItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get it now.
        /// </summary>
        public static string String_GetItNow {
            get {
                return ResourceManager.GetString("String_GetItNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string String_Home {
            get {
                return ResourceManager.GetString("String_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile .
        /// </summary>
        public static string String_Mobile {
            get {
                return ResourceManager.GetString("String_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +84 903 086 171.
        /// </summary>
        public static string String_MobileNumber {
            get {
                return ResourceManager.GetString("String_MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Help.
        /// </summary>
        public static string String_OnlineHelp {
            get {
                return ResourceManager.GetString("String_OnlineHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Range.
        /// </summary>
        public static string String_PriceRange {
            get {
                return ResourceManager.GetString("String_PriceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string String_Product {
            get {
                return ResourceManager.GetString("String_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string String_Review {
            get {
                return ResourceManager.GetString("String_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your review here!.
        /// </summary>
        public static string String_ReviewDescription {
            get {
                return ResourceManager.GetString("String_ReviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string String_Search {
            get {
                return ResourceManager.GetString("String_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string String_Service {
            get {
                return ResourceManager.GetString("String_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new materials - clever designs - new technologies.
        /// </summary>
        public static string String_Slogan {
            get {
                return ResourceManager.GetString("String_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Networking.
        /// </summary>
        public static string String_SocialNetworking {
            get {
                return ResourceManager.GetString("String_SocialNetworking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string String_Submit {
            get {
                return ResourceManager.GetString("String_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string String_View {
            get {
                return ResourceManager.GetString("String_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View details.
        /// </summary>
        public static string String_ViewDetail {
            get {
                return ResourceManager.GetString("String_ViewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Tan Nhat Trung Co. Ltd.
        /// </summary>
        public static string String_Welcome {
            get {
                return ResourceManager.GetString("String_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home | Tan Nhat Trung Co. Ltd.
        /// </summary>
        public static string Title_Home {
            get {
                return ResourceManager.GetString("Title_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product | Tan Nhat Trung Co. Ltd.
        /// </summary>
        public static string Title_Product {
            get {
                return ResourceManager.GetString("Title_Product", resourceCulture);
            }
        }
    }
}
